// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLsnqnjjL3cvez37oYBSnNVMQeEwsW-WQ',
    appId: '1:675798186704:web:d27ad1d6f9344870b27cd5',
    messagingSenderId: '675798186704',
    projectId: 'chat-app-3a320',
    authDomain: 'chat-app-3a320.firebaseapp.com',
    storageBucket: 'chat-app-3a320.appspot.com',
    measurementId: 'G-J4XS4HQJ5Y',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcOkfLLWa3wq5Jw9jOmUz0ZpbnyG6RxEk',
    appId: '1:675798186704:android:4b23a3fca5552ea5b27cd5',
    messagingSenderId: '675798186704',
    projectId: 'chat-app-3a320',
    storageBucket: 'chat-app-3a320.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZxz3B3w1SuH-sl1UdaI661ToDZ9T-23k',
    appId: '1:675798186704:ios:b0167cc12f8e49dcb27cd5',
    messagingSenderId: '675798186704',
    projectId: 'chat-app-3a320',
    storageBucket: 'chat-app-3a320.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZxz3B3w1SuH-sl1UdaI661ToDZ9T-23k',
    appId: '1:675798186704:ios:b0167cc12f8e49dcb27cd5',
    messagingSenderId: '675798186704',
    projectId: 'chat-app-3a320',
    storageBucket: 'chat-app-3a320.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLsnqnjjL3cvez37oYBSnNVMQeEwsW-WQ',
    appId: '1:675798186704:web:3c2b62a79b0693e6b27cd5',
    messagingSenderId: '675798186704',
    projectId: 'chat-app-3a320',
    authDomain: 'chat-app-3a320.firebaseapp.com',
    storageBucket: 'chat-app-3a320.appspot.com',
    measurementId: 'G-QX75138G8D',
  );
}
